#!/usr/bin/env node
/**
 * Reads the version from package.json and writes it to:
 *   - install/inno/version.iss (Inno Setup #include)
 *   - .claude/skills/orchestrate/SKILL.md (frontmatter version field)
 *
 * Run: node scripts/sync-version.js
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf-8'));
const version = pkg.version;

// Sync to Inno Setup version.iss
const issContent = `; Auto-generated by scripts/sync-version.js — do not edit manually\n#define MyAppVersion   "${version}"\n`;
fs.writeFileSync(path.join(root, 'install', 'inno', 'version.iss'), issContent, 'utf-8');
console.log(`Version synced: ${version} → install/inno/version.iss`);

// Sync to SKILL.md frontmatter
const skillPath = path.join(root, '.claude', 'skills', 'orchestrate', 'SKILL.md');
if (fs.existsSync(skillPath)) {
  let skill = fs.readFileSync(skillPath, 'utf-8');
  if (skill.match(/^version:\s*.+$/m)) {
    skill = skill.replace(/^version:\s*.+$/m, `version: ${version}`);
  } else {
    // Insert version after the name field
    skill = skill.replace(/^(name:\s*.+)$/m, `$1\nversion: ${version}`);
  }
  fs.writeFileSync(skillPath, skill, 'utf-8');
  console.log(`Version synced: ${version} → .claude/skills/orchestrate/SKILL.md`);
}
