#!/usr/bin/env node
/**
 * Reads the version from package.json and writes it to installer/version.iss
 * so Inno Setup can #include it at compile time.
 *
 * Run: node scripts/sync-version.js
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf-8'));
const version = pkg.version;

const issContent = `; Auto-generated by scripts/sync-version.js — do not edit manually\n#define MyAppVersion   "${version}"\n`;
fs.writeFileSync(path.join(root, 'installer', 'version.iss'), issContent, 'utf-8');

console.log(`Version synced: ${version} → installer/version.iss`);
